# Generated by Django 4.0.4 on 2022-05-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ememergy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ememergy',
            options={'ordering': ['created_at'], 'verbose_name': 'Ёбаная хуйня', 'verbose_name_plural': 'Ёбаные хуйни'},
        ),
        migrations.AlterField(
            model_name='ememergy',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='ememergy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='ememergy',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано ли???'),
        ),
        migrations.AlterField(
            model_name='ememergy',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='ФОТО'),
        ),
        migrations.AlterField(
            model_name='ememergy',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='ememergy',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
