# Generated by Django 4.0.4 on 2022-05-24 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ememergy', '0003_category_ememergy_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ememergy',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='ememergy',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ememergy.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ememergy',
            name='content',
            field=models.TextField(blank=True, verbose_name='Дрочь'),
        ),
        migrations.AlterField(
            model_name='ememergy',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Запузырено'),
        ),
        migrations.AlterField(
            model_name='ememergy',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Тема'),
        ),
    ]
