# Generated by Django 4.0.4 on 2022-05-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ememergy', '0004_alter_ememergy_options_alter_ememergy_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ememergy',
            name='is_published',
            field=models.BooleanField(verbose_name='Запузырено'),
        ),
    ]
