# Generated by Django 4.0.4 on 2022-05-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ememergy', '0005_alter_ememergy_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ememergy',
            name='is_published',
            field=models.BooleanField(default=None, verbose_name='Запузырено'),
        ),
    ]
