# Generated by Django 4.0.4 on 2022-06-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ememergy', '0007_alter_ememergy_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ememergy',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Запузырено'),
        ),
    ]
