# Generated by Django 4.0.4 on 2022-06-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ememergy', '0008_alter_ememergy_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ememergy',
            options={'ordering': ['-created_at']},
        ),
    ]
