# Generated by Django 4.0.4 on 2022-06-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ememergy', '0009_alter_ememergy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ememergy',
            name='content',
            field=models.CharField(blank=True, max_length=20000, verbose_name='Дрочь'),
        ),
    ]
